[build]
  command = "bun run build"
  publish = "out"

[build.environment]
  BUN_INSTALL = "bun i"
  NODE_VERSION = "20"
  BUN_VERSION = "latest"
  NPM_FLAGS = "--ignore-scripts"

[functions]
  node_bundler = "esbuild" 